/*REV.  0.1 (pmg.)   1st August 2003
  ADuC845.h MCV Software Group, Analog Devices Inc.*/

/*  BYTE Registers  */
__sfr __at (0x80) P0;
__sfr __at (0x81) SP;
__sfr __at (0x82) DPL;
__sfr __at (0x83) DPH;
__sfr __at (0x84) DPP;
__sfr __at (0x87) PCON;
__sfr __at (0x88) TCON;
__sfr __at (0x89) TMOD;
__sfr __at (0x8A) TL0;
__sfr __at (0x8B) TL1;
__sfr __at (0x8C) TH0;
__sfr __at (0x8D) TH1;
__sfr __at (0x90) P1;
__sfr __at (0x98) SCON;
__sfr __at (0x99) SBUF;
__sfr __at (0x9A) I2CDAT;
__sfr __at (0x9B) I2CADD;
__sfr __at (0x9D) T3FD;
__sfr __at (0x9E) T3CON;
__sfr __at (0xA0) P2;
__sfr __at (0xA1) TIMECON;
__sfr __at (0xA2) HTSEC;
__sfr __at (0xA3) SEC;
__sfr __at (0xA4) MIN;
__sfr __at (0xA5) HOUR;
__sfr __at (0xA6) INTVAL;
__sfr __at (0xA7) DPCON;
__sfr __at (0xA8) IE;
__sfr __at (0xA9) IEIP2;
__sfr __at (0xAE) PWMCON;
__sfr __at (0xAF) CFG848;
__sfr __at (0xB0) P3;
__sfr __at (0xB1) PWM0L;
__sfr __at (0xB2) PWMOH;
__sfr __at (0xB3) PWM1L;
__sfr __at (0xB4) PWM1H;
__sfr __at (0xB7) SPH;
__sfr __at (0xB8) IP;
__sfr __at (0xB9) ECON;
__sfr __at (0xBC) EDATA1;
__sfr __at (0xBD) EDATA2;
__sfr __at (0xBE) EDATA3;
__sfr __at (0xBF) EDATA4;
__sfr __at (0xC0) WDCON;
__sfr __at (0xC2) CHIPID;
__sfr __at (0xC6) EADRL;
__sfr __at (0xC7) EADRH;
__sfr __at (0xC8) T2CON;
__sfr __at (0xCA) RCAP2L;
__sfr __at (0xCB) RCAP2H;
__sfr __at (0xCC) TL2;
__sfr __at (0xCD) TH2;
__sfr __at (0xD0) PSW;
__sfr __at (0xD1) ADCMODE;
__sfr __at (0xD2) ADC0CON1;
__sfr __at (0xD4) SF;
__sfr __at (0xD5) ICON;
__sfr __at (0xD7) PLLCON;
__sfr __at (0xD8) ADCSTAT;
__sfr __at (0xD9) ADC0L;
__sfr __at (0xDA) ADC0M;
__sfr __at (0xDB) ADC0H;
__sfr __at (0xDF) PSMCON;
__sfr __at (0xE0) ACC;
__sfr __at (0xE1) OF0L;
__sfr __at (0xE2) OF0M;
__sfr __at (0xE3) OF0H;
__sfr __at (0xE6) ADC0CON2;
__sfr __at (0xE8) I2CCON;
__sfr __at (0xE8) DCON;
__sfr __at (0xE9) GN0L;
__sfr __at (0xEA) GN0M;
__sfr __at (0xEB) GN0H;
__sfr __at (0xF0) B;
__sfr __at (0xF2) I2CADD1;
__sfr __at (0xF7) SPIDAT;
__sfr __at (0xF8) SPICON;
__sfr __at (0x9F) EWAIT; 
__sfr __at (0xAF) CFG847; 

/*  BIT Registers  */
/*  PSW  (0xD0)*/
__sbit __at (0xD7) CY;
__sbit __at (0xD6) AC;
__sbit __at (0xD5) F0;
__sbit __at (0xD4) RS1;
__sbit __at (0xD3) RS0;
__sbit __at (0xD2) OV;
__sbit __at (0xD1) F1;
__sbit __at (0xD0) P;
/*  TCON  (0x88)*/
__sbit __at (0x8F) TF1;
__sbit __at (0x8E) TR1;
__sbit __at (0x8D) TF0;
__sbit __at (0x8C) TR0;
__sbit __at (0x8B) IE1;
__sbit __at (0x8A) IT1;
__sbit __at (0x89) IE0;
__sbit __at (0x88) IT0;
/*  IE  (0xA8)*/
__sbit __at (0xAF) EA;
__sbit __at (0xAE) EADC;
__sbit __at (0xAD) ET2;
__sbit __at (0xAC) ES;
__sbit __at (0xAB) ET1;
__sbit __at (0xAA) EX1;
__sbit __at (0xA9) ET0;
__sbit __at (0xA8) EX0;
/*  IP (0xB8) */
//_sbit PS1   = IP ^ 7;
__sbit __at (0xBE) PADC;
__sbit __at (0xBD) PT2;
__sbit __at (0xBC) PS;
__sbit __at (0xBB) PT1;
__sbit __at (0xBA) PX1;
__sbit __at (0xB9) PT0;
__sbit __at (0xB8) PX0;
/*  P3  (0xB0)*/
__sbit __at (0xB7) RD;
__sbit __at (0xB6) WR;
__sbit __at (0xB5) T1;
__sbit __at (0xB4) T0;
__sbit __at (0xB3) INT1;
__sbit __at (0xB2) INT0;
__sbit __at (0xB1) TXD;
__sbit __at (0xB0) RXD;
/*  SCON  (0x98)*/
__sbit __at (0x9F) SM0;
__sbit __at (0x9E) SM1;
__sbit __at (0x9D) SM2;
__sbit __at (0x9C) REN;
__sbit __at (0x9B) TB8;
__sbit __at (0x9A) RB8;
__sbit __at (0x99) TI;
__sbit __at (0x98) RI;
/*  P1  (0x90)*/
__sbit __at (0x91) T2EX;
__sbit __at (0x90) T2;

/*  T2CON  (0xC8)*/
__sbit __at (0xCF) TF2;
__sbit __at (0xCE) EXF2;
__sbit __at (0xCD) RCLK;
__sbit __at (0xCC) TCLK;
__sbit __at (0xCB) EXEN2;
__sbit __at (0xCA) TR2;
__sbit __at (0xC9) CNT2;
__sbit __at (0xC8) CAP2;
/*  WDCON  (0xC0)*/
__sbit __at (0xC7) PRE3;
__sbit __at (0xC6) PRE2;
__sbit __at (0xC5) PRE1;
__sbit __at (0xC4) PRE0;
__sbit __at (0xC3) WDIR;
__sbit __at (0xC2) WDS;
__sbit __at (0xC1) WDE;
__sbit __at (0xC0) WDWR;
/*  ADCSTAT  (0xD8)*/
__sbit __at (0xDF) RDY0;
__sbit __at (0xDE) RDY1;
__sbit __at (0xDD) CAL;
__sbit __at (0xDC) NOXREF;
__sbit __at (0xDB) ERR0;
__sbit __at (0xDA) ERR1;
/*  I2CCON  (0xE8)*/
__sbit __at (0xEF) MDO;
__sbit __at (0xEE) MDE;
__sbit __at (0xED) MCO;
__sbit __at (0xEC) MDI;
__sbit __at (0xEB) I2CM;
__sbit __at (0xEA) I2CRS;
__sbit __at (0xE9) I2CTX;
__sbit __at (0xE8) I2CI;
/*  DCON (0xE8) */
__sbit __at (0xEF) D1;
__sbit __at (0xEE) D1EN;
__sbit __at (0xED) D0;
__sbit __at (0xEB) D0EN;
/*  SPICON  (0xF8) */
__sbit __at (0xFF) ISPI;
__sbit __at (0xFE) WCOL;
__sbit __at (0xFD) SPE;
__sbit __at (0xFC) SPIM;
__sbit __at (0xFB) CPOL;
__sbit __at (0xFA) CPHA;
__sbit __at (0xF9) SPR1;
__sbit __at (0xF8) SPR0;
